# Generated by Django 4.2 on 2025-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hradmin",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
