# Generated by Django 4.2 on 2025-06-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("sl", models.IntegerField(default=0)),
                ("cl", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
            ],
        ),
    ]
