# Generated by Django 4.1.13 on 2025-06-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_create_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='employee',
            field=models.ForeignKey(db_column='employee', on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
